[package]
name = "cosmic-client-toolkit"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmic-protocols = { path = "../" }
sctk = { package = "smithay-client-toolkit", git = "https://github.com/Smithay/client-toolkit", rev = "69bffe5" }
wayland-client = { version = "0.30.0" }
smithay = { git = "https://github.com/Smithay/smithay", rev = "c85e1e5", default-features = false, features = ["backend_egl", "renderer_gl", "renderer_multi", "slog-stdlog"], optional = true }

[build-dependencies]
gl_generator = { version = "0.14.0", optional = true }

[dev-dependencies]
futures = "0.3.24"
cascade = "1"
env_logger = "0.9.1"
gdk-pixbuf = "0.15.11"
glow = "0.11.2"
glutin = "0.30.0"
gtk4 = { version = "0.4.8", features = ["v4_6"] }
gdk4-wayland = { version = "0.4.8", features = ["wayland_crate", "v4_4", "egl"] }
iced = { version = "0.5.2", features = ["image"] }
nix = "0.25.0"
raw-window-handle = "0.5.0"
wayland-backend = { version = "0.1.0", features = ["client_system"] }
winit = "0.27.4"

[features]
default = ["gl", "smithay"]
gl = ["gl_generator"]

[[example]]
name = "gtk-capture"
required-features = ["smithay"]
